import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/providers/auth-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import ConvexClientProvider from "@/components/providers/client-convex-provider";
import { Providers } from "@/components/providers/nextui-provider";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "sonner";
import { EdgeStoreProvider } from "@/lib/edgestore";
export const metadata: Metadata = {
  title: "Magic Keyboard",
  description: "Generated by Nevir",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ConvexClientProvider>
          <EdgeStoreProvider>
            <AuthProvider>
              <Providers>
                <ThemeProvider attribute="class" defaultTheme="dark">
                  <Toaster richColors invert />
                  {children}
                </ThemeProvider>
              </Providers>
            </AuthProvider>
          </EdgeStoreProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
